db:
  PATH_DATASETS: C:\Users\roizi\PycharmProjects\pythonProject2\project_1\data\raw
  url_1: https
  url_2: https


training_process:
  max_epochs: 1000
  batch_size: 128
  criterion:
  optimizer:
  lr: 1e-3
  lr_dim_reduction:
  gates_learning: False  # if false gates parameters will be non-trainable
  alpha: 0.1
  sigma_x: 1
  sigma_y: 1
  lambda_x: 1e-5
  lambda_y: 1e-5

  layers:
    in_layer: [28, 28]
    out_layer: 10
    dropout:
    dropout_val:

testing_process:

trained_model:
  final_models_dir: C:\Users\roizi\PycharmProjects\pythonProject2\project_1\models
  tb_save_dir: C:\Users\roizi\PycharmProjects\pythonProject2\project_1\src\visualization
